# Site settings
title: Alex Kadis
# email: alex@kadis.me
description: > # this means to ignore newlines until "baseurl:"
  I&rsquo;m a software developer, Jew, geek, and advocate.

baseurl: "" # the subpath of your site, e.g. /blog/

url: "https://alexkadis.com" # the base hostname & protocol for your site
destination: "../alexkadis-com"
keep_files: 
  - "_misc"
  - ".well-known"
  - "maze"

sass:
    sass_dir: ./_sass

plugins:
  - jekyll-paginate
paginate: 5
paginate_path: "/blog/page-:num/"

# baseurl: "/ak2015/_site/" # the subpath of your site, e.g. /blog/
# url: "http://localhost:8888/ak2015/_site/"

# bluesky_username: alexkadis
github_username: alexkadis
linkedin_username: akadis

# Build settings
markdown: kramdown
krandown:
  parse_block_html: true

# markdown: redcarpet
# redcarpet:
  # extensions: ["strikethrough"]

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "portfolio"
      type: "pages" # previously `page` in Jekyll 2.2.
    values:
      layout: "portfolio" # overrides previous default layout
      author: "Alex Kadis"
      category: "portfolio"
